package linguagensac2.views;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import linguagensac2.connection.MySQL;
import linguagensac2.controladores.UsuarioDAO;
import linguagensac2.modelos.Usuario;
import linguagensac2.views.FuncionariosTela;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Caio_Viper
 */
public class telaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    public telaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSenhaNova = new javax.swing.JPasswordField();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        txtCelular = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(714, 600));
        setMinimumSize(new java.awt.Dimension(714, 600));
        setPreferredSize(new java.awt.Dimension(737, 600));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "AUTENTICAÇÃO DE USUÁRIO"));
        jPanel1.setLayout(null);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(243, 195, 0, 0);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/entrar.png"))); // NOI18N
        jLabel2.setText("Login:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(24, 225, 80, 24);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/senha.png"))); // NOI18N
        jLabel3.setText("Senha:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(26, 267, 80, 24);

        txtLogin.setToolTipText("Email");
        jPanel1.add(txtLogin);
        txtLogin.setBounds(118, 226, 143, 22);
        jPanel1.add(txtSenha);
        txtSenha.setBounds(118, 268, 143, 22);

        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/entrar1.png"))); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar);
        btnEntrar.setBounds(80, 330, 120, 31);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logoprincipal.png.jpg"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(55, 89, 188, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(6, 6, 290, 526);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "CADASTRO DE USUÁRIO"));
        jPanel2.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/usuario.png"))); // NOI18N
        jLabel4.setText("Nome");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(12, 39, 170, 24);
        jPanel2.add(txtNome);
        txtNome.setBounds(12, 69, 215, 22);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sexo.png"))); // NOI18N
        jLabel5.setText("Sexo");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(260, 40, 90, 24);

        cbxCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino", "Outros" }));
        jPanel2.add(cbxCombo);
        cbxCombo.setBounds(260, 70, 130, 22);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cpf.png"))); // NOI18N
        jLabel6.setText("CPF");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(12, 109, 100, 24);

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtCpf);
        txtCpf.setBounds(12, 139, 150, 22);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/email.png"))); // NOI18N
        jLabel7.setText("E-mail");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(12, 187, 110, 24);
        jPanel2.add(txtEmail);
        txtEmail.setBounds(12, 217, 215, 22);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cel.png"))); // NOI18N
        jLabel8.setText("Celular");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(260, 110, 100, 24);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/senha.png"))); // NOI18N
        jLabel10.setText("Senha");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(12, 267, 110, 24);
        jPanel2.add(txtSenhaNova);
        txtSenhaNova.setBounds(12, 303, 125, 22);

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/addusuario.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCadastrar);
        btnCadastrar.setBounds(37, 447, 150, 31);

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/apagar.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpar);
        btnLimpar.setBounds(219, 447, 150, 31);

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtCelular);
        txtCelular.setBounds(260, 140, 130, 22);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(310, 10, 410, 520);

        setSize(new java.awt.Dimension(737, 554));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        Usuario novoUsuario = new Usuario();
        MySQL mysql = new MySQL("localhost:3306", "controletech", "root", "Bico1346@");
        mysql.conectaBanco();
        UsuarioDAO usuarioDAO = new UsuarioDAO(mysql);
        
        novoUsuario.setNome(txtNome.getText());

        novoUsuario.setCpf(txtCpf.getText());

        novoUsuario.setEmail(txtEmail.getText());

        novoUsuario.setCelular(txtCelular.getText());

        novoUsuario.setSexo(String.valueOf(cbxCombo.getSelectedItem()));

        novoUsuario.setSenha(String.valueOf(txtSenhaNova.getPassword()));
        

        
        try {
            usuarioDAO.cadastraUsuario(novoUsuario);
            JOptionPane.showMessageDialog(null,"Usuário Cadastrado Com Sucesso!");
        } catch (SQLException ex) {
            Logger.getLogger(telaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Falha ao Cadastrar usuario");
        } finally {
            mysql.fechaBanco();
        }
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        Usuario usuario = new Usuario();
        MySQL mysql = new MySQL("localhost:3306", "controletech", "root", "Bico1346@");
        mysql.conectaBanco();
        UsuarioDAO usuarioDAO = new UsuarioDAO(mysql);
        FuncionariosTela funcionariosTela = new FuncionariosTela();
        telaPrincipal telaPrincipal = new telaPrincipal();
        
        
        try {
            if(usuarioDAO.autenticarUsuario(txtLogin.getText(), String.valueOf(txtSenha.getPassword())) == true) {
                JOptionPane.showMessageDialog(null,"Usuário Autenticado! Seja Bem-Vindo");
                LimparCampos();
                funcionariosTela.setVisible(true);
                telaPrincipal.setVisible(false);
                                
            } else {
                JOptionPane.showMessageDialog(null,"Usuário Não Autenticado!");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(telaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            mysql.fechaBanco();
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        LimparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void LimparCampos(){
        txtCelular.setText("");
        txtCpf.setText("");
        txtEmail.setText("");
        txtNome.setText("");
        txtSenhaNova.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cbxCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtSenhaNova;
    // End of variables declaration//GEN-END:variables
}
